### ISSUE TITLE
Merged PR doesn't close ticket

### ISSUE THREAD

**Issue by zoispag** [bobvanderlinden/probot-auto-merge#112]
Hi, 

I noticed the following behavior today. A PR set to be auto-merged via label and with `Closes #xxxx` (issue number) in the description, is getting merged when all checks are passed, but the issue remains open.
Although I think it is strange, because GitHub keyword "closes" connects the issue with the PR, but maybe when the PR is merged via an API call and bot via the button Merge, GitHub doesn't respect the keywords.

**Comment by bobvanderlinden** [comment]
Hmm, interesting. You're right. I would've thought GitHub would pick this up, as I'm using the API equivalent to pressing the merge button (https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button). It isn't as equivalent as the documentation makes it out to be.

Handling these cases manually will not really result in full desired behavior, as auto-merge can only close issues within the same repository and does not directly have rights to do this for other repositories.

Maybe the new API for merging pull request (which is currently in preview stage) does handle your described case, but it isn't documented as such (https://developer.github.com/v4/previews/#pull-requests-preview). 

Until GitHub implements the merge button behavior properly, An option for this behavior would be nice though. I will look into this when I get some more time for auto-merge. PRs on this are very welcome!

**Comment by zoispag** [comment]
It is quite important this one for us, so I will try to take a look next week, when I am back from holidays, if you haven’t already! Thanks!

**Comment by jonhue** [comment]
I contacted GitHub support as this also is an important issue for me. They said that this app is missing `issues:write` permissions and thus the close operation on issues is failing. 

@bobvanderlinden could you update these permissions?

**Comment by bobvanderlinden** [comment]
@jonhue that makes sense. I've updated the permissions :+1: Thanks for contacting GitHub!

**Comment by zoispag** [comment]
![](https://media.giphy.com/media/1GrsfWBDiTN60/giphy.gif)

**Comment by zoispag** [comment]
Just tested it! Can confirm that it works. We can close the issue :)
Thanks both @bobvanderlinden and @jonhue

**Comment by bobvanderlinden** [comment]
Haha nice :D Thanks for the confirmation! I'll close this one :+1:
