### ISSUE TITLE
Access to code seems to be an excessive permission

### ISSUE THREAD

**Issue by dawhum** [bobvanderlinden/probot-auto-merge#134]
If the extension really needs to access the code, please could you clarify why that is?

**Comment by bobvanderlinden** [comment]
It needs access to code to be able to merge PRs on top of master. In addition it needs access to merge master onto the PR branch.

I have not found a way to do this without the permissions, but if you find a way to circumvent these permissions please let me know!

**Comment by dawhum** [comment]
Thank you, @bobvanderlinden. I really appreciate the detailed explanation.
