### ISSUE TITLE
Self-hosting instructions

### ISSUE THREAD

**Issue by webratz** [bobvanderlinden/probot-auto-merge#177]
Hi,

due to some reasons i need to self host this probot.
I have it up and running (also receiving webhooks) but nothing seems to happen. Could you maybe provide some infos:

* list of required permissions and webhooks to be configured in the app
* how to get debug output (using `LOG_LEVEL=debug` did not help a lot)
* further hints on how to debug

**Comment by webratz** [comment]
The issue on my side was launching it with `/app/node_modules/.bin/probot run -p 9000` instead of `/app/node_modules/.bin/probot run -p 9000 ./lib/index.js`

**Comment by bobvanderlinden** [comment]
Thanks for the feedback. Good to hear it worked out.

Is the `./lib/index.js` part documented at `probot` somewhere?

**Comment by webratz** [comment]
i basically just looked it up in the `package.json` so that might not count as documented.
