### ISSUE TITLE
Bot closes a PR without any visible explanation

### ISSUE THREAD

**Issue by italux** [bobvanderlinden/probot-auto-merge#184]
Today I observe a behaviour where a PR with several `no pass` status was closed by `probot-auto-merge`

![image](https://user-images.githubusercontent.com/144831/53508753-206e0800-3a99-11e9-85c9-f56275ea7cc4.png)

Looking into that I realised that seems that the bot closes the PR after the base branch / PR was closed and deleted

**Comment by bobvanderlinden** [comment]
Was the PR based on a branch that was deleted by any chance? I have noticed this same thing myself and was surprised because auto-merge does not have functionality to close PRs.

**Comment by italux** [comment]
@bobvanderlinden Sorry for my delay in responding here (_more than a year, hehe_), sorry for that, but I'm not currently using the bot anymore, but yes, the PR based on a deleted brach
