### ISSUE TITLE
Bot performed merge even with outstanding requested changes

### ISSUE THREAD

**Issue by BenBirt** [bobvanderlinden/probot-auto-merge#210]
It's very possible we're doing something wrong, would appreciate some pointers! It seems as though the bot did a merge even though there were outstanding comments on the approving review: https://github.com/dataform-co/dataform/pull/145

Our bot config is here: https://github.com/dataform-co/dataform/blob/master/.github/auto-merge.yml

@G2H for visibility

**Comment by bobvanderlinden** [comment]
From what I'm seeing in the pr and the config, the bot worked like it should. There was one approval review (which also included some comments) and there were no 'changes requested'-reviews. From the config this should result in a merge. Comment-reviews are neutral, so they are not counted for the merge.

What was the intended behavior?

**Comment by BenBirt** [comment]
Ahh, okay, thanks, that makes sense. I don't think we understood that there were different types of reviews, to be honest.

The intended behaviour was that _any_ outstanding comment (regardless of the type of review) would block auto-merge. Is there any way of setting that up?

**Comment by bobvanderlinden** [comment]
Hmm, no. Currently there is no support for 'unresolved' code comments. It does sound like something that would be a nice addition. Could you create an issue for this?

**Comment by BenBirt** [comment]
Sure, thanks! https://github.com/bobvanderlinden/probot-auto-merge/issues/211
