### ISSUE TITLE
bot is not automatically merging

### ISSUE THREAD

**Issue by tracom1** [bobvanderlinden/probot-auto-merge#266]
We have this problem (we are running our own copy of your bot) where auto-merge is not occurring.  This only occurs with certain repos.

The repository is private, we have branch protections in place that requires status checks (basically that integration tests have been completed).  When the bot initially runs, it will not merge and then states that "not all status checks have passed".  However, if I wait until after the build has completed, and then remove and re-add a tag, it will then auto-merge.  

I'm not sure how to work around this error.  We do not have "Require branches to be up to date before merging" selected as part of our rule settings, but I'm not sure if adding this would resolve the problem or not.

**Comment by yale** [comment]
@bobvanderlinden I've noticed a couple of things, which I've been investigating in our own fork:

1. We're not listening to the commit `status` event. I think this is important because the repositories that we're working with do not use check suites that are managed by Github apps; rather, the statuses are updated via webhooks. The result is that the PR is not re-enqueued once, say, CircleCI completes.

2. The bot is only looking at `CheckSuite`s and not at the commit's `StatusContext`, so it can't correctly match against required checks. In my case, we have several required checks:

```
"requiredStatusCheckContexts": [
    "ci/circleci: build",
    "ci/circleci: flow",
    "ci/circleci: prettier",
    "ci/circleci: test",
    "ci/circleci: loki",
    "ci/circleci: lint_styles",
    "ci/circleci: lint_source",
    "ci/circleci: lint_tests"
]
``` 

but none of those appear under check suites. They instead appear under `commit.status.contexts` in Graphql:

```
"commits": {
  "nodes": [
    {
      "commit": {
          "status": {
              "contexts": [
                  {
                      "context": "ci/circleci: puppeteer",
                      "state": "FAILURE"
                  },
                  {
                      "context": "Danger",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: build",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: danger",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: dependencies",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: deploy",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: flow",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: lint_source",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: lint_styles",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: lint_tests",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: loki",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: prettier",
                      "state": "SUCCESS"
                  },
                  {
                      "context": "ci/circleci: test",
                      "state": "SUCCESS"
                  }
              ]
          },
```

LMK what you think of the above.

**Comment by bobvanderlinden** [comment]
Oh wow, that's a big oversight. I wasn't aware that `commit.status.contexts` was a good alternative to the CheckSuite API. This matches perfectly to `requiredStatusCheckContexts`, which I was struggling to match to CheckSuite API.

I'm not sure I have time in the coming days to look into this, but I will give it a go if there are no PRs.

Just to give me some docs for next time:

https://developer.github.com/v3/activity/events/types/#statusevent
https://developer.github.com/v4/input_object/updatebranchprotectionruleinput/
https://developer.github.com/v4/object/status/

Thanks a lot for notifying me about this! It might even lessen the need for waiting for pending PRs.

**Comment by yale** [comment]
@bobvanderlinden I took a stab, though there are no tests and the code can definitely be clearer 😅 I'll get a PR out momentarily.

**Comment by tracom1** [comment]
I've attempted to use the branch, but unfortunately, we're still having the same problems with auto-merge.  I think yale's suggestion might be what's needed.

**Comment by tracom1** [comment]
Do we have an anticipated merge date?

**Comment by tracom1** [comment]
Hi Bob, I was wondering if there has been any movement with this issue?

**Comment by tracom1** [comment]
We've switched to using the most recent upstream code, but we're still having the problem where the code isn't auto-merging.  We still have the same message:

"The pull request is blocked by a failing or missing check."

How frequently will it recheck based on an update for check_suite or check_run?

We currently have a required branch protection of "continuous-integration/jenkins/pr-merge" and it's taking about 5 minutes to run, but I see the auto-merge check only happening once, in the beginning.

**Comment by tracom1** [comment]
For a little bit more information -- Following the webhooks from our app, I see a `check_run` and `check_suite` running at the beginning of the creation of the PR.  Both of these are listed as `completed`, even though the integration tests are still in progress. (I can provide the payload if you need it)  The integration tests take roughly 5 minutes to run.  After those 5 minutes, I do not see another webhook created.

**Comment by bobvanderlinden** [comment]
More information on this is very much appreciated. A test that more accurately represents the real behaviour of GitHub would be most helpful. Would something like this be possible to reproduce?

**Comment by tracom1** [comment]
I'm not sure.  I suppose I could try and get all the payload messages that were sent by the webhook and try resending them to my locally running instance.  I attempted to do that with the `status` event and even when I tried passing in `LOG_LEVEL=trace` into my docker container, I unfortunately didn't see anything additional being logged during that time.

For a little more information, we run our own version of your probot-auto-merge in our organization, but it pulls the latest code.  This is done because most of our repositories are private.

Here's just a very small snippet of the status message sent which I would expect triggers another pass of the auto-merge code:

```{
  "id": 7531747332,
  "sha": "f9cc8c156fc2b177dbf7351f4ff6c84beb52b9dc",
  "name": "<private repo>",
  "target_url": "https://<private jenkins url>",
  "avatar_url": "https://avatars3.githubusercontent.com/u/35454792?v=4",
  "context": "continuous-integration/jenkins/branch",
  "description": "This commit looks good",
  "state": "success",```

Let me know how else you think I can best help in preparing this test.  I'd love to help.

**Comment by tracom1** [comment]
I've replicated a scenario, and waded through all the payload messages that are sent by the webhook of the app.  I hope this is helpful:

8:35:58 _pull_request_ - event triggered for repo
8:35:58 _pull_request_ - event triggered for repo 2nd time (there are two events, with different sha1)
8:35:59 _check_suite_ - completed for repo
8:35:59 _check_run_ - created for repo
8:35:59 _check_run _ -  completed for repo
8:36:17 _status_  - jenking/branch pending "the commit is being built"
8:36:18 _status_ - jenkins/pr-merge pending "This commit is being built"
8:37:02 _status_ - jenkins/branch pending "This commit is being built"
8:37:24 _status_ - jenkins/pr-merge pending "This commit is being built"
8:37:36 _status_ - jenkins/branch pending "This commit is being built"
8:37:57 _status_  - jenkins/pr-merge pending "This commit is being built"
8:38:34 _status_ - jenkins/branch success "This commit looks good"
8:39:59 _status_ - jenkins/pr-merge success "This commit looks good"

**Comment by tracom1** [comment]
Once this has done, it will not merge.  However, if I remove a required_label and then re-add it, it is triggered to auto-merge the code.

Here's the webhook information for the removal and additional of the label:

_pull_request_ - event triggered for repo.  

Here's the result

```There are failing conditions:

✓ blockingChecks
✓ blockingLabels
✓ blockingTitle
✓ maximumChangesRequested
✓ mergeable
✓ minimumApprovals
✓ open
✘ requiredLabels: Required labels are missing (docker)```

When I re-add the docker-label, another _pull_request_ even is triggered, and it merges

**Comment by FrittenToni** [comment]
Hi, 

I am running the app internally on github enterprise as well and face the same issue too. For me the auto-merge is not working if a status event with state "success" appears. The check stays red and only if I delete and add the required label again or when I updated my pull request description the auto-merge happens. Not sure if it helps but this is the event that doesn't trigger an auto-merge:

```
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/c62fa51
X-GitHub-Delivery: 663187ea-e386-11e9-8a42-7e835d70da84
X-GitHub-Enterprise-Host: some-enterprise-github.corp
X-GitHub-Enterprise-Version: 2.17.5
X-GitHub-Event: status
X-Hub-Signature: sha1=0cf1baad07e3f72be7c775062b35684341eedd66
Payload
{
  "id": 58568136,
  "sha": "3f390f2e2fd75fd49780d01a76e6e86e715f022d",
  "name": "some-org/some-repository",
  "target_url": "https://some-target.com/job/some-repository/job/PR-19/3/display/redirect",
  "context": "continuous-integration/jenkins/pr-merge",
  "description": "This commit looks good",
  "state": "success",
  "commit": {
    "sha": "3f390f2e2fd75fd49780d01a76e6e86e715f022d",
    "node_id": "MDY6Q29tbWl0MjcxNjYzOjNmMzkwZjJlMmZkNzVmZDQ5NzgwZDAxYTc2ZTZlODZlNzE1ZjAyMmQ=",
    "commit": {
      "author": {
        "name": "pioneers-probot-auto-merge[bot]",
        "email": "pioneers-probot-auto-merge[bot]@users.noreply.some-enterprise-github.corp",
        "date": "2019-09-30T13:07:47Z"
      },
      "committer": {
        "name": "GitHub Enterprise",
        "email": "noreply-github@sap.com",
        "date": "2019-09-30T13:07:47Z"
      },
      "message": "Merge master into PR-2",
      "tree": {
        "sha": "5f295eb312b4afb38002cc208e03f356e82d82d6",
        "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/trees/5f295eb312b4afb38002cc208e03f356e82d82d6"
      },
      "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/commits/3f390f2e2fd75fd49780d01a76e6e86e715f022d",
      "comment_count": 0,
      "verification": {
        "verified": false,
        "reason": "unsigned",
        "signature": null,
        "payload": null
      }
    },
    "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/commits/3f390f2e2fd75fd49780d01a76e6e86e715f022d",
    "html_url": "https://some-enterprise-github.corp/some-org/some-repository/commit/3f390f2e2fd75fd49780d01a76e6e86e715f022d",
    "comments_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/commits/3f390f2e2fd75fd49780d01a76e6e86e715f022d/comments",
    "author": {
      "login": "pioneers-probot-auto-merge[bot]",
      "id": 55217,
      "node_id": "MDM6Qm90NTUyMTc=",
      "avatar_url": "https://some-enterprise-github.corp/avatars/u/2402?",
      "gravatar_id": "",
      "url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D",
      "html_url": "https://some-enterprise-github.corp/github-apps/pioneers-probot-auto-merge",
      "followers_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/followers",
      "following_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/following{/other_user}",
      "gists_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/subscriptions",
      "organizations_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/orgs",
      "repos_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/repos",
      "events_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://some-enterprise-github.corp/api/v3/users/pioneers-probot-auto-merge%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "committer": null,
    "parents": [
      {
        "sha": "d542d28ed6c6b63d5cbacbbdef9913734c6541e9",
        "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/commits/d542d28ed6c6b63d5cbacbbdef9913734c6541e9",
        "html_url": "https://some-enterprise-github.corp/some-org/some-repository/commit/d542d28ed6c6b63d5cbacbbdef9913734c6541e9"
      },
      {
        "sha": "6a209c65f9f1e0181e63b2c472bafd306021383b",
        "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/commits/6a209c65f9f1e0181e63b2c472bafd306021383b",
        "html_url": "https://some-enterprise-github.corp/some-org/some-repository/commit/6a209c65f9f1e0181e63b2c472bafd306021383b"
      }
    ]
  },
  "branches": [
    {
      "name": "PR-2",
      "commit": {
        "sha": "3f390f2e2fd75fd49780d01a76e6e86e715f022d",
        "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/commits/3f390f2e2fd75fd49780d01a76e6e86e715f022d"
      },
      "protected": false
    }
  ],
  "created_at": "2019-09-30T13:29:59+00:00",
  "updated_at": "2019-09-30T13:29:59+00:00",
  "repository": {
    "id": 271663,
    "node_id": "MDEwOlJlcG9zaXRvcnkyNzE2NjM=",
    "name": "some-repository",
    "full_name": "some-org/some-repository",
    "private": false,
    "owner": {
      "login": "some-org",
      "id": 2402,
      "node_id": "MDQ6VXNlcjI0MDI=",
      "avatar_url": "https://some-enterprise-github.corp/avatars/u/2402?",
      "gravatar_id": "",
      "url": "https://some-enterprise-github.corp/api/v3/users/some-org",
      "html_url": "https://some-enterprise-github.corp/some-org",
      "followers_url": "https://some-enterprise-github.corp/api/v3/users/some-org/followers",
      "following_url": "https://some-enterprise-github.corp/api/v3/users/some-org/following{/other_user}",
      "gists_url": "https://some-enterprise-github.corp/api/v3/users/some-org/gists{/gist_id}",
      "starred_url": "https://some-enterprise-github.corp/api/v3/users/some-org/starred{/owner}{/repo}",
      "subscriptions_url": "https://some-enterprise-github.corp/api/v3/users/some-org/subscriptions",
      "organizations_url": "https://some-enterprise-github.corp/api/v3/users/some-org/orgs",
      "repos_url": "https://some-enterprise-github.corp/api/v3/users/some-org/repos",
      "events_url": "https://some-enterprise-github.corp/api/v3/users/some-org/events{/privacy}",
      "received_events_url": "https://some-enterprise-github.corp/api/v3/users/some-org/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://some-enterprise-github.corp/some-org/some-repository",
    "description": "A simple java app to be used to test piper",
    "fork": false,
    "url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository",
    "forks_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/forks",
    "keys_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/keys{/key_id}",
    "collaborators_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/collaborators{/collaborator}",
    "teams_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/teams",
    "hooks_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/hooks",
    "issue_events_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/issues/events{/number}",
    "events_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/events",
    "assignees_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/assignees{/user}",
    "branches_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/branches{/branch}",
    "tags_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/tags",
    "blobs_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/blobs{/sha}",
    "git_tags_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/tags{/sha}",
    "git_refs_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/refs{/sha}",
    "trees_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/trees{/sha}",
    "statuses_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/statuses/{sha}",
    "languages_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/languages",
    "stargazers_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/stargazers",
    "contributors_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/contributors",
    "subscribers_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/subscribers",
    "subscription_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/subscription",
    "commits_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/commits{/sha}",
    "git_commits_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/git/commits{/sha}",
    "comments_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/comments{/number}",
    "issue_comment_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/issues/comments{/number}",
    "contents_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/contents/{+path}",
    "compare_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/compare/{base}...{head}",
    "merges_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/merges",
    "archive_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/{archive_format}{/ref}",
    "downloads_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/downloads",
    "issues_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/issues{/number}",
    "pulls_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/pulls{/number}",
    "milestones_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/milestones{/number}",
    "notifications_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/notifications{?since,all,participating}",
    "labels_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/labels{/name}",
    "releases_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/releases{/id}",
    "deployments_url": "https://some-enterprise-github.corp/api/v3/repos/some-org/some-repository/deployments",
    "created_at": "2019-05-06T11:14:44Z",
    "updated_at": "2019-09-30T13:07:36Z",
    "pushed_at": "2019-09-30T13:09:17Z",
    "git_url": "git://some-enterprise-github.corp/some-org/some-repository.git",
    "ssh_url": "git@some-enterprise-github.corp:some-org/some-repository.git",
    "clone_url": "https://some-enterprise-github.corp/some-org/some-repository.git",
    "svn_url": "https://some-enterprise-github.corp/some-org/some-repository",
    "homepage": null,
    "size": 29,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  "enterprise": {
    "id": 1,
    "slug": "sap-se",
    "name": "SAP SE",
    "node_id": "MDg6QnVzaW5lc3Mx",
    "avatar_url": "https://some-enterprise-github.corp/avatars/b/1?",
    "description": null,
    "website_url": null,
    "html_url": "https://some-enterprise-github.corp/businesses/sap-se",
    "created_at": "2019-03-16T05:31:15Z",
    "updated_at": "2019-03-16T05:31:15Z"
  },
  "sender": {
    "login": "some-org",
    "id": 2402,
    "node_id": "MDQ6VXNlcjI0MDI=",
    "avatar_url": "https://some-enterprise-github.corp/avatars/u/2402?",
    "gravatar_id": "",
    "url": "https://some-enterprise-github.corp/api/v3/users/some-org",
    "html_url": "https://some-enterprise-github.corp/some-org",
    "followers_url": "https://some-enterprise-github.corp/api/v3/users/some-org/followers",
    "following_url": "https://some-enterprise-github.corp/api/v3/users/some-org/following{/other_user}",
    "gists_url": "https://some-enterprise-github.corp/api/v3/users/some-org/gists{/gist_id}",
    "starred_url": "https://some-enterprise-github.corp/api/v3/users/some-org/starred{/owner}{/repo}",
    "subscriptions_url": "https://some-enterprise-github.corp/api/v3/users/some-org/subscriptions",
    "organizations_url": "https://some-enterprise-github.corp/api/v3/users/some-org/orgs",
    "repos_url": "https://some-enterprise-github.corp/api/v3/users/some-org/repos",
    "events_url": "https://some-enterprise-github.corp/api/v3/users/some-org/events{/privacy}",
    "received_events_url": "https://some-enterprise-github.corp/api/v3/users/some-org/received_events",
    "type": "User",
    "site_admin": false
  },
  "installation": {
    "id": 152,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTUy"
  }
}
```

**Comment by FrittenToni** [comment]
Hi @bobvanderlinden, Hi @tracom1,

I had a little bit more time to investigate into the problem. I can confirm that probot receives the status event and that the app tries to handle it. From my observations the issue happens [here](https://github.com/bobvanderlinden/probot-auto-merge/blob/b1843e22fe583b67ecbc1bb2dfed16fd64a22892/src/index.ts#L107-L108).

In my concrete example the pullRequestResponses object in [line 100](https://github.com/bobvanderlinden/probot-auto-merge/blob/b1843e22fe583b67ecbc1bb2dfed16fd64a22892/src/index.ts#L100) contains the following data:
´´´
[{"status":200,"url":"https://my-enterprise-github.corp/api/v3/repos/someOrg/some-repo/pulls?base=auto-merge-pr-1","headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type","cache-control":"private, max-age=60, s-maxage=60","connection":"close","content-length":"2","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Mon, 14 Oct 2019 09:07:41 GMT","etag":"\"f5975357d9669e60c9d587cba7ca2956\"","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"GitHub.com","status":"200 OK","strict-transport-security":"max-age=31536000; includeSubdomains","vary":"Accept, Authorization, Cookie, X-GitHub-OTP","x-content-type-options":"nosniff","x-frame-options":"deny","x-github-enterprise-version":"2.17.5","x-github-media-type":"github.v3; format=json","x-github-request-id":"bca675cd-bf2e-4249-b289-af9c629c17ff","x-ratelimit-limit":"50001","x-ratelimit-remaining":"49997","x-ratelimit-reset":"1571047574","x-runtime-rack":"0.053194","x-xss-protection":"1; mode=block"},"data":[]}]
´´´
As you can see the data property of the response object is an empty array. [Line 107](https://github.com/bobvanderlinden/probot-auto-merge/blob/b1843e22fe583b67ecbc1bb2dfed16fd64a22892/src/index.ts#L107) tries to retrieve the response.data object but since it is empty the result is an empty pullRequests array and therefore the handlePullRequests function in [line 109](https://github.com/bobvanderlinden/probot-auto-merge/blob/b1843e22fe583b67ecbc1bb2dfed16fd64a22892/src/index.ts#L109) will never be called.

So now my question is whether this is a bug inside the code or if github enterprise just behaves differently and sends different responses than the normal github.

**Comment by FrittenToni** [comment]
Hi @bobvanderlinden,

I found out why the response is always empty for me. As of now you are calling the pull request API with a parameter called "base" [here](https://github.com/bobvanderlinden/probot-auto-merge/blob/b1843e22fe583b67ecbc1bb2dfed16fd64a22892/src/index.ts#L104). This parameter points to the branch (auto-merge-pr1) which I want to merge to master but the API is always returning an empty array.

According to [GitHub documentation](https://developer.github.com/v3/pulls/) the base branch is supposed to be the branch where you want to merge your changes into. In my case this is the master branch.

After hard coding the base parameter value to master, the code merge is happening for me on status success event.

**Comment by bobvanderlinden** [comment]
Thanks a lot for the detective work @FrittenToni! Based on your findings I made a PR that should resolve issues regarding status events not being handled correctly. @FrittenToni has confirmed this is working. It is now running on production, so any feedback on missing merges from anyone else is highly appreciated.

**Comment by tracom1** [comment]
Thanks so much for your work @FrittenToni !  I never found time to be able to dig around into this on my own, so you really saved the day.

**Comment by tracom1** [comment]
Just a quick update, we pulled from upstream, and now unfortunately none of our PRs work and we receive the following error.  
```Error while processing pull request Scout24/fizz-probot-auto-merge#39: Error: No permission to fetch status```

We're debugging more fully into why we are now getting this error, and I'll provide updates when we have more information.  I've already tried updating the permissions for the app we have added into our org.

**Comment by tracom1** [comment]
It's definitely raising here:

https://github.com/bobvanderlinden/probot-auto-merge/blob/cb2483ed05450b4651f9e4b2892b1a0d38decf9a/src/github-models.ts#L104, but I'm not familiar enough with what has changed that would now cause this to be a problem.  We last built on October 3rd.

**Comment by tracom1** [comment]
We are running this locally now to reproduce the problem, and it appears our status is null, which is causing this to error:

```{ repository:
   { pullRequest:
      { number: 1,
        state: 'OPEN',
        mergeable: 'MERGEABLE',
        mergeStateStatus: 'CLEAN',
        potentialMergeCommit: { oid: '238402b1e258458927cac3423fed2a2ff8ea2083' },
        reviews: { nodes: [] },
        labels: { nodes: [ { name: 'bug' }, { name: 'enhancement' } ] },
        title: 'Update README.md',
        authorAssociation: 'OWNER',
        baseRef:
         { repository: { owner: { login: 'LarsFronius' }, name: 'shitty-probot-test' },
           target: { oid: '40353cac136161dfa7072c78f8daca71226de085' },
           name: 'master' },
        baseRefOid: '40353cac136161dfa7072c78f8daca71226de085',
        commits:
         { nodes:
            [ { commit:
                 { status: null,
                   checkSuites:
                    { nodes:
                       [ { app: { databaseId: 43683 },
                           status: 'QUEUED',
                           conclusion: null,
                           checkRuns: { nodes: [] } } ] } } } ] },
        headRef:
         { repository: { owner: { login: 'LarsFronius' }, name: 'shitty-probot-test' },
           target: { oid: 'ef4c1923f6cf5c2d6977f55590fb87725c27b0f9' },
           name: 'LarsFronius-patch-1' },
        headRefOid: 'ef4c1923f6cf5c2d6977f55590fb87725c27b0f9',
        repository: { branchProtectionRules: { nodes: [] } } } } }```

**Comment by bobvanderlinden** [comment]
Somehow auto-merge doesn't have permission to fetch the status section of the GraphQL query:

```
        {
            "locations": [
                {
                    "column": 13,
                    "line": 44
                }
            ],
            "message": "Resource not accessible by integration",
            "path": [
                "repository",
                "pullRequest",
                "commits",
                "nodes",
                0,
                "commit",
                "status"
            ],
            "type": "FORBIDDEN"
        }
```

**Comment by tracom1** [comment]
This is not just a problem for enterprise repositories, we were able to reproduce it with an individuals private repository.

Will there be a plan to revert this change so it once again works for private repositories, or should we figure out an alternative solution on our own?

**Comment by bobvanderlinden** [comment]
I reverted the change that was fetching statuses. I do think it's basically a specific permission that needs to be enabled in the github app, but I already set `Read-Only` permissions for `Commit Status`. Probably more is needed. Will look into this when I have some more time again.

**Comment by tracom1** [comment]
Thanks!  If it helps, the first thing we worked on adding was additional permissions.  We didn't change Commit statuses to `Read & Write`, but I gave additional `Read-Only` permissions to `Deployments` and `Pages`.

We already had `Read & Write` access to `Checks`, `Contents`, `Issues`, and `Pull requests`

**Comment by tracom1** [comment]
I've been testing this change and unfortunately, it still doesn't work for us.  I've forked the repo and added some additional logging, and it appears the problem comes from the GraphQL query.  When I run the query manually from this function (https://github.com/bobvanderlinden/probot-auto-merge/blob/master/src/index.ts#L96) with insomnia, and using my owner credentials, I get the result I expect.  However, when I run the query through the app and then add a simple logging line afterwards `console.log(`${repo} has the following ${result.data} for the refs/heads/${branchName}`)`, my response is that `result.data` is simply stating `undefined` and then returning an empty `[]` which of course prevents the method from being re-triggered.

**Comment by tracom1** [comment]
Added some more logging and it looks like the variables aren't defined in the query, here's the error message I'm seeing when adding `${JSON.stringify(result.errors)}` to my log message:

```[{"path":["query","repository","owner"],"extensions":

{"code":"variableNotDefined","variableName":"owner"}
,"locations":[\{"line":3,"column":27}],"message":"Variable $owner is used by but not declared"},{"path":["query","repository","name"],"extensions":

{"code":"variableNotDefined","variableName":"repo"}
,"locations":[\{"line":3,"column":41}],"message":"Variable $repo is used by but not declared"},{"path":["query","repository","ref","qualifiedName"],"extensions":

{"code":"variableNotDefined","variableName":"refQualifiedName"}
,"locations":[\{"line":4,"column":30}],"message":"Variable $refQualifiedName is used by but not declared"}]```

I change the line [98](https://github.com/bobvanderlinden/probot-auto-merge/blob/master/src/index.ts#L98) to the following:

`query ($owner: String!, $repo: String!, $refQualifiedName: String!) {` and now I'm getting data in my result now. I'm still testing if this change now causes the method to work and update after running a CI build

**Comment by tracom1** [comment]
So I've verified that the status check does trigger a handlePullRequest event.  In one instance, it did result in auto-merging, in another instance while it did result in re-checking of the PR, the result was `neutral` even though all the checks should have been passing.

**Comment by bobvanderlinden** [comment]
@tracom1 Thanks a lot for the investigations. Since this was such a obvious problem (which the tests unfortunately could not catch) I've made sure my testing repository now has SemaphoreCI 2, which _does_ emit `status` events whereas modern TravisCI does not. I've now confirmed that #435 works on that repository.

If you have a specific owner/repo and pull request number I can check out why auto-merge did not go through with merging.

**Comment by tracom1** [comment]
Hey Bob, with regards to the other one failing, it turns out it was a result of branch protections the team had put in place, that prevented the app from being allowed to merge.  I fixed that and everything looks good!  I think we're finally ready to close this ticket. ;-) . Thanks for all your help
