### ISSUE TITLE
BOT SUDDENLY STOPS WORKING AGAIN

### ISSUE THREAD

**Issue by dareojo** [bobvanderlinden/probot-auto-merge#373]
Probot auto merge suddenly stopped working since yesterday again. Is there a way to make this work seamlesly and stable?

Kindly advise. Nothing has changed in the Repository..

Thank you

**Comment by bobvanderlinden** [comment]
Please keep focus in the appropriate issue. Creating duplicate issues doesn't help the cause. #366
