### ISSUE TITLE
Add option to only run/not run on certain branches

### ISSUE THREAD

**Issue by Daniel-Griffiths** [bobvanderlinden/probot-auto-merge#431]
I am not sure if it's possible but it would be super handy if there was an option to only run probot-auto-merge on specific branches

For example I may only want it to run on the `master` branch. Or do the opposite where I want it to run on every branch that is is **not** `master` (eg feature branches)

Thanks for creating this super handy bot! :slightly_smiling_face:

**Comment by bobvanderlinden** [comment]
I'm not sure what you're asking. Are you referring to only handling PRs that have a specific base branch?

**Comment by Daniel-Griffiths** [comment]
No worries! As an example if I only wanted code to be auto merged on a feature branch the workflow 's might look a little bit like this:

*Allow a merge*
I open a new pull request, the branch is called `/feature/my-cool-feature` and the base branch it's being merged into is called `develop`. I would like Probot to merge this PR as the current branch is not `master` or `develop`

*Dont allow merge*
I open a new PR to merge `develop` into the base branch `master`, since the current name develop is in the list of banned branch names, I would not wan't Probot to automatically merge this PR.

An example config for this scenario might look something like this (using js as psudo code)

`dissallowedBranches: ['develop', 'master']`

Or the inverse might look like

`allowedBranches: ['/feature/(.*)']`

**Comment by epDHowwD** [comment]
Awesome progress! Will `allowedBranches` in combination with rules allow to configure branches separately? 

**Use Case:** Let's say I want to use auto merge on all branches with basic rules, like a collaborator has to approve, a label has to be set. On the `release` branch I want to enforce fast-forward-only and would like to activate `updateBranch: true`, but only on the release branch, as it would be a waste of resources on any other branch.

**Comment by bobvanderlinden** [comment]
Unfortunately, it's not possible to set `updateBranch` for individual rules. I do see the value in the use-case though.
