### ISSUE TITLE
PR is not merged

### ISSUE THREAD

**Issue by entropitor** [bobvanderlinden/probot-auto-merge#51]
Hey, I'm having a problem where the PR is updated but then it isn't merged afterwards. Is there anyway to debug why the bot is not working?

**Comment by bobvanderlinden** [comment]
I still have to work on status reporting for the bot, but I see this happening sometimes as well. It might be that the bot is still waiting for another PRs tests to complete, but it could also be a bug.

Status reporting would at least help in both cases.

**Comment by snarfed** [comment]
hi! we're seeing this problem too. a PR was reviewed and passed the rules in our config, but the bot didn't merge it.

just to confirm, the probot-auto-merge app in the github marketplace, https://github.com/apps/probot-auto-merge , is hosted, right? ie we don't need to deploy an instance ourselves, we just install it, and add a config file to our repo, and it should run?

cc @youssefm

**Comment by bobvanderlinden** [comment]
I've made some changes to the bot that should resolve some of the problems. Most notably, whenever an error occurs, the bot would not handle further queued pull requests.

That said, I'm seeing that a repostiory from your company (@snarfed) cannot be queried somehow. I have expanded on the error reporting so that I get some more info about why it isn't able to query. Will keep you updated.

**Comment by entropitor** [comment]
@bobvanderlinden Is this supposed to work with private repositories? That's where we are using it

**Comment by bobvanderlinden** [comment]
Yes, I'm using it for a private repository as well and it seems to be working fine.

I improved the error reporting a bit last time and am now able to see that the GraphQL query result sometimes has `null` for a pull request' `headRef`. Without the `headRef` the bot is currently not able to fetch the checks/CI status of the PR.

In #61 I added a bit more validation for the `headRef` and add more information to the validation error that is thrown in return.

What I'm leaning towards currently is that you're using forks and the bot does not have permission for those forks, so it is unable to fetch the `headRef` of the PR as it resides inside the fork and not the main repo. I still need to find whether this is actually the case, but if so I'll do some searching in the GitHub permissions.

**Comment by bobvanderlinden** [comment]
I just got the full query result from pull request of @snarfed and I think my earlier suspicion was correct. Not only is the `headRef` `undefined`, but the same goes for the `mergeable` field. Both are related to knowing the code of the other repository. Without permission, Github correctly shields the bot from retrieving any status information of that fork.

The `mergeable` field is quite important for probot-auto-merge to determine whether to start the merge. I have not tried it, but I presume executing the merge itself will probably also not be allowed (as it 'moves' private code into a repository that _is_ visible).

I still need to look into whether there is a convenient way to give the bot permission to forks of a repository, but currently I'm afraid this situation is just unsupported.

**Comment by bobvanderlinden** [comment]
I've made https://github.com/bobvanderlinden/probot-auto-merge/issues/64 to have a more specific issue for status reporting of the bot. That should help people in the future know why the bot isn't merging a PR.

**Comment by entropitor** [comment]
@bobvanderlinden We are not using a fork

**Comment by bobvanderlinden** [comment]
@entropitor Hmm. Have you tried this again today as well? I only see an error from 2 Oct from your organisation.

**Comment by gtmanfred** [comment]
Hrm, it would be really nice for probot to be able to report errors.

@bobvanderlinden would you mind taking a look for this PR for us?  https://github.com/saltstack/salt-jenkins/pull/1162

Thanks!
Daniel

**Comment by bobvanderlinden** [comment]
@gtmanfred auto-merge doesn't look at the `CODEOWNERS` file yet! It looks at the association of the reviewers. You can see what the bot is using using the following graphql query on https://developer.github.com/v4/explorer/:

```
query { 
  repository(owner: "saltstack", name: "salt-jenkins") {
    pullRequest(number: 1162){
      reviews(last: 100) {
        nodes {
          author { login }
          authorAssociation
        }
      }
    }
  }
}
```

In your case there is one `MEMBER` and one `CONTRIBUTOR`.

**Comment by gtmanfred** [comment]
ahh awesome! thanks!

**Comment by gtmanfred** [comment]
So would the owner be just the "saltstack" org?  Even if we are all part of the org do we not get counted as owners?

**Comment by bobvanderlinden** [comment]
That's probably correct. See https://developer.github.com/v4/enum/commentauthorassociation/ for some information about this. I currently do not have a organisation where I'm the owner, so it's a bit tricky to figure it out without full documentation on this topic.

**Comment by entropitor** [comment]
> @entropitor Hmm. Have you tried this again today as well? I only see an error from 2 Oct from your organisation.

@bobvanderlinden We might not have done one that day, but I just had to close a PR with a merge label because the bot didn't

**Comment by bobvanderlinden** [comment]
@rallytime That PR has 1 contributor and 1 member that have approved the changes. A contributor is considered a lower association than a member and thus that doesn't match the 2 member rule. Make Ch3LL a member and you should be good. Changing the rule to allow contributors can be a bit dangerous.

**Comment by gtmanfred** [comment]
Based on your query above, @ch3ll is a MEMBER.

```
{
  "data": {
    "repository": {
      "pullRequest": {
        "reviews": {
          "nodes": [
            {
              "author": {
                "login": "gtmanfred"
              },
              "authorAssociation": "MEMBER"
            },
            {
              "author": {
                "login": "Ch3LL"
              },
              "authorAssociation": "MEMBER"
            }
          ]
        }
      }
    }
  }
}
```

**Comment by bobvanderlinden** [comment]
Ok, I think there is a problem here. From my perspective `Ch3LL` is a contributor and not a member:

```
{
  "data": {
    "repository": {
      "pullRequest": {
        "reviews": {
          "nodes": [
            {
              "author": {
                "login": "gtmanfred"
              },
              "authorAssociation": "MEMBER"
            },
            {
              "author": {
                "login": "Ch3LL"
              },
              "authorAssociation": "CONTRIBUTOR"
            }
          ]
        }
      }
    }
  }
}
```

I guess, because the bot only has permission to that repository, that it does not know about private organisation members and thus the bot will see only public members as members.

I dug a bit into the permission system of Github and found "Organisation members", a right that the bot did not have earlier. I have added that read-only right, so once you update that right for the bot it *should* be able to know who's a (private) member as well.

**Comment by gtmanfred** [comment]
Ok, i have accepted that permission change and closed and reopened that issue.

Thanks for your help, i will let you know if it works.

**Comment by entropitor** [comment]
ORGANISATION_MEMBER works for me!

But right now, I updated the permissions so we have direct access to the repo, I also have the problem that the status reporting says "Merging" but it doesn't actually merge

**Comment by entropitor** [comment]
@bobvanderlinden Do you have any idea why the bot is not merging even when it thinks it should be okay?

**Comment by bobvanderlinden** [comment]
I looked at the errors upon merging and there are multiple different ones:

* Merge commits are not allowed on this repository
* Bad credentials
* You're not authorized to push to this branch
* 2 of 3 required status checks are pending

For datacamp, Github is consistently returning: You're not authorized to push to this branch. Next best thing I can do is report these errors in the bots status.

**Comment by entropitor** [comment]
When you say bad credentials and "you're not authorized to push to this branch", is there something we can do about that?

**Comment by bobvanderlinden** [comment]
I'm not sure what the problem is for those errors. Bad credentials seems to suggest that somehow the credentials get mixed up, but I have not determined why or how that happens yet. 'You're not authorized' might be the same cause, but again, not sure on these ones. They happen randomly it seems and I cannot reproduce it yet for my own repo.

**Comment by entropitor** [comment]
@bobvanderlinden We had master as a protected branch with write protection. We disabled that now but that was causing the authorization issues

**Comment by bobvanderlinden** [comment]
Hmm, in that case I might be missing some of the other protected branch conditions. The error doesn't really make sense though, but I guess it's a very generic one.

**Comment by treylon** [comment]
We also run into the issue of not being able to protect branches or the bot will fail with the same error. Do you have any updates on this @bobvanderlinden ?

**Comment by bobvanderlinden** [comment]
@treylon Have you set up the minimum number of reviews in probot-auto-merge to a lower number than the one you configured in GitHubs protected branch? In that case probot-auto-merge will try to merge even if that isn't possible yet according to GitHub.

**Comment by bobvanderlinden** [comment]
#84 should solve the issue of "2 of 3 required status checks are pending" errors.

Also, I found a bug regarding checking review approvals where the review's `submittedAt` date was incorrectly not fetched from GitHub. See #83.

**Comment by bobvanderlinden** [comment]
@entropitor Could you create a separate issue for organisation members? I'd like to close this issue and create more specific ones.

**Comment by entropitor** [comment]
I've created one for mine: https://github.com/bobvanderlinden/probot-auto-merge/issues/85

**Comment by mardet** [comment]
> I still need to look into whether there is a convenient way to give the bot permission to forks of a repository, but currently I'm afraid this situation is just unsupported.

Hi @bobvanderlinden, did you ever find the time to look into this?
We are stuck since the tool doesn't work with forks. We are trying to give the right permissions to the app without succeeding for now. Any suggestions of what we could try?
