### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by fgisslen** [bobvanderlinden/probot-auto-merge#676]
Hi,
I can't get this to work.

I have installed the auto-merge through github marketplace.
And when I give a PR the label merge nothing happens.

Is there any steps that I am missing?

my /.github/auto-merge.yml look like this:
updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

requiredLabels:
- merge

mergeCommitMessage: |
  {title} (#{number})
  {body}

**Comment by bobvanderlinden** [comment]
Just to be sure, can you create a new PR and look whether auto-merge shows up in the checks of the PR? Otherwise the configuration file is broken (or reportStatus is unset).

**Comment by fgisslen** [comment]
@bobvanderlinden Thanks, I got it to work. Is it possible to force it to wait for my jenkins CI to respond with successful test? Now it just merge when there is no pending test showing. And it's not showing pending test for my jenkins.

**Comment by bobvanderlinden** [comment]
Make the CI required to merge PRs in GitHub under protected branches.

**Comment by fgisslen** [comment]
@bobvanderlinden Thx!
