### ISSUE TITLE
running probot-auto-merge in aws not working

### ISSUE THREAD

**Issue by haghabozorgi** [bobvanderlinden/probot-auto-merge#735]
we are trying to test running prorun-auto-merge in our kube cluster.  

we built the docker container and pushed to our registry.
we pass API_ID, WEBHOOK_SECRET, and PRIVATE_KEY_PATH as env var to container, 
we have nginx-ingress-controller (aws elb) in front of the service that serves the container, and use an ingress definition to route traffic to the service. 

We see the POST and "webhook received" messages in the probot logs, but the app does not show up in the repo in the PR or under 'checks' tab, so the app does not seem to work at all. The app is installed as suggested in the probot docs, and we have double-checked the permissions. Not sure if the elb is causing an issue with a missing/mangled header? Any suggestions would be appreciated

**Comment by haghabozorgi** [comment]
upon further investigation the .env was generated during the docker build and only includes a webhook_proxy_url value set to smee.io, which I thought might be causing the issue with probot not working, so I fix the container so it mounts .env file to /app/auto-merge/env with API_ID, WEBHOOK_SECRET, and PRIVATE_KEY_PATH vars only, and upon startup i get 

```
Unable to connect to smee.io, try restarting your server.
```
the container is still running and seems to still receive webhooks from github, but still not working. Is there not a way to run probot-auto-merge without smee.io, or am I missing something?

We setup bulldozer bot inside of the same cluster and that seems to be working as expected, so I do not think it is related to being behind an aws elb as my original comments mentioned.

**Comment by haghabozorgi** [comment]
closing, issue was with .env config.

**Comment by bobvanderlinden** [comment]
What did you do specifically to solve the issue? Delete .env?

**Comment by haghabozorgi** [comment]
@bobvanderlinden thanks for follow-up. Being an idiot... had the var as API_ID instead of APP_ID, the probot container logs did not seem to imply anything was wrong though, so I did not catch the mistake. I would have expected the probot container to log, no APP_ID specified and throw an error, or something similar. 

In terms of the original issue I filed, I do think the .env file being generated in the container during runtime was a bit unexpected, and given it populates a WEBHOOK_PROXY_URL pointing to smee.io url, since we are not using smee.io, I would imagine this could potentially cause issues??? Since probot would be hitting the web proxy url but github would be sending directly to probot?

I am glad to report that we do have it running in our kube cluster and things are working. Thank you for your time and effort on this project. Since I have your ear, do you have any plans on adding support for merge conflicts? basically, remove the automerge label and make a comment in the pr that there is a merge conflict?

**Comment by bobvanderlinden** [comment]
Thanks for the follow-up!

> Since I have your ear, do you have any plans on adding support for merge conflicts? basically, remove the automerge label and make a comment in the pr that there is a merge conflict?

That sounds like a separate feature. Auto-merge doesn't comment at the moment, so this would be something entirely new. It does sound like a valid use-case to keep people in the loop (instead of missing the auto-merge check silently failing).

Would you like to create an issue that describes the behaviour and the specific use-case?
