### ISSUE TITLE
Waiting for CI

### ISSUE THREAD

**Issue by guy-lud** [bobvanderlinden/probot-auto-merge#79]
Hi, 

I wounder can `probot-auto-merge` wait for Some CI result as part of the rules ?

**Comment by bobvanderlinden** [comment]
That's a good suggestion. I can imagine that configuring which checks are required for auto merge is quite essential in some use cases. This could be a separate condition for the bot to block merges.

I'm still working on another feature, but like always a PR is very welcome.

**Comment by guy-lud** [comment]
I'll try to do so
