### ISSUE TITLE
[Feature Request] Add "requiredLabelsRegex" and "blockingLabelsRegex" options

### ISSUE THREAD

**Issue by rogerluan** [bobvanderlinden/probot-auto-merge#809]
Pretty self descriptive 😄 these would allow us to change e.g.:

```
blockingLabels:
 - "blocked: dependency"
 - "blocked: design"
 - "blocked: backend"
 - "pending review"
 - "pending QA"
```

To:

```
blockingLabelsRegex:
  - "blocked(.*)"
  - "pending(.*)"
```

`requiredLabelsRegex` should be pretty similar to this.

I intend to implement this feature and open a PR for it 👍

**Comment by bobvanderlinden** [comment]
This is a common theme. Supporting both regex and non-regex cases. I made a suggestion here: https://github.com/bobvanderlinden/probot-auto-merge/pull/768#pullrequestreview-448692490

Basically I was thinking of doing the following:

```yaml
blockingLabels:
  - non regex label
  - regex: ^regex label$
```

Let me know whether this is fitting for you as well.

**Comment by rogerluan** [comment]
It would, but I implemented it as a new option already 🙈 
I'm learning typescript on the fly using this project, so it'd take some time for me to figure out how to refactor the current code I have up. If you have any guidance on how to accomplish that, I'd happily refactor if you think this is still relevant!

This issue got auto-closed by my PR in my org's repo but I'll reopen it and open the PR against this repo now that I've tested my solution and it's in production 😁
