### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by entropitor** [bobvanderlinden/probot-auto-merge#85]
If master is a protected branch where only some people have write access, the bot says "Merging" but doens't actually do anything. Internally there are "Bad Credentials" error messages ((source)[https://github.com/bobvanderlinden/probot-auto-merge/issues/51#issuecomment-433687408]), to the user of the bot it's very confusing.

"Necessary" fix:
Better error messages

Ideal fix:
Requests permission to be able to push to protected branches

**Comment by bobvanderlinden** [comment]
Is this still an issue for you? auto-merge now makes use of a new GitHub API (https://developer.github.com/v4/previews/#mergeinfopreview---more-detailed-information-about-a-pull-requests-merge-state) which should avoid incorrectly merging branches when GitHub is blocking merges.

**Comment by entropitor** [comment]
I'll try it out and let you know if it didn't work :smile:
