### ISSUE TITLE
Remove event-stream from dependencies

### ISSUE THREAD

**Issue by dkhmelenko** [bobvanderlinden/probot-auto-merge#96]
I would strongly recommend to update dependencies simply by `npm update`, because of the issue https://github.com/dominictarr/event-stream/issues/116 discovered recently. After you run `nmp update` the dependency `event-stream` will disappear from package-lock.json file and you will not have any Alerts from Github about potential vulnerability.

**Comment by bobvanderlinden** [comment]
Nice coincidence. Yes I also ran into this issue. I had some trouble using `npm audit fix`: https://npm.community/t/npm-audit-fails-with-enoaudit-on-500-response/3629

I first created a PR to update `nodemon` to resolve `npm audit fix` issues #94 . Then I ran `npm audit fix` #95

**Comment by bobvanderlinden** [comment]
This should be resolved now.
