### ISSUE TITLE
Error while processing PR

### ISSUE THREAD

**Issue by dkhmelenko** [bobvanderlinden/probot-auto-merge#97]
I'm getting time to time the following error on each event for some PRs
```
Error while processing pull request organization/pull_request#5565: { Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v4"}
    at response.text.then.message (/app/node_modules/@octokit/rest/lib/request/request.js:72:19)
```

Did you face it? Do you know where is the problem and how could it be fixed?

**Comment by bobvanderlinden** [comment]
#240 has a good explanation for this issue. I'm going to close this one and continue in #240.
